name: C++ Unit Tests and Coverage

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ cmake libgtest-dev lcov gcovr

    - name: Build and Run Tests with Coverage Flags
      run: |
        mkdir -p build
        cd build
        g++ -c -fprofile-arcs -ftest-coverage -O0 -std=c++14 -I../src -I/usr/include/gtest ../src/calculator.cpp -o calculator.o
        g++ -c -fprofile-arcs -ftest-coverage -O0 -std=c++14 -I../src -I/usr/include/gtest ../tests/calculator_test.cpp -o calculator_test.o
        g++ -fprofile-arcs -ftest-coverage -O0 calculator.o calculator_test.o -lgtest -lgtest_main -pthread -o runTests
        ./runTests

    - name: Generate Coverage Report (gcov)
      run: |
        cd build
        echo "Running gcov..."
        gcov calculator.o || true
        echo "Listing .gcov files:"
        ls -l *.gcov || true
        echo "Showing content of calculator.cpp.gcov:"
        cat calculator.cpp.gcov || echo "No .gcov file generated"

    - name: Upload Coverage Report Artifact
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: build/*.gcov

